converted to GHA
plus3it/terraform-aws-watchmaker pull request #398
Opened 2023-02-24 22:23 UTC by johnricords

2023-02-24 22:36 UTC, johnricords commented
mockstack test is disable for release, module requires an array of vars

2023-02-24 22:49 UTC, lorengordon requested changes
See comment for custom workflow used by this project.

2023-02-24 22:49 UTC, lorengordon commented on .travis.yml
> -      script: make cfn/version VERSION=$RELEASE_VERSION
This project has a "custom" job that will require a new workflow, running `make cfn/version VERSION=$RELEASE_VERSION`... It's unique to this project, so I think just add a new workflow file that is triggered on both pull_request and workflow_call to run that command. Then update the release.yaml workflow to call that workflow as a reusable job, with `needs` on the release job. That should chain everything together well enough.

2023-03-28 16:23 UTC, lorengordon commented
go codebuild go

2023-03-28 17:30 UTC, merged